/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 26/09/2016 21:04:02
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            16000000
#define MX_HSE_VALUE                            25000000
#define MX_EXTERNAL_CLOCK_VALUE                 12288000
#define MX_SYSCLKFreq_VALUE                     216000000
#define MX_HCLKFreq_Value                       216000000
#define MX_FCLKCortexFreq_Value                 216000000
#define MX_CortexFreq_Value                     216000000
#define MX_AHBFreq_Value                        216000000
#define MX_APB1Freq_Value                       54000000
#define MX_APB2Freq_Value                       108000000
#define MX_APB1TimFreq_Value                    108000000
#define MX_APB2TimFreq_Value                    216000000
#define MX_EthernetFreq_Value                   216000000
#define MX_CECFreq_Value                        32786
#define MX_LCDTFToutputFreq_Value               96000000
#define MX_I2C1Freq_Value                       54000000
#define MX_I2C2Freq_Value                       54000000
#define MX_I2C3Freq_Value                       54000000
#define MX_I2C4Freq_Value                       54000000
#define MX_I2SFreq_Value                        192000000
#define MX_SAI1Freq_Value                       192000000
#define MX_SAI2Freq_Value                       192000000
#define MX_SDMMCFreq_Value                      216000000
#define MX_RTCFreq_Value                        32000
#define MX_USART1Freq_Value                     108000000
#define MX_USART2Freq_Value                     54000000
#define MX_USART3Freq_Value                     54000000
#define MX_UART4Freq_Value                      54000000
#define MX_UART5Freq_Value                      54000000
#define MX_UART8Freq_Value                      54000000
#define MX_UART7Freq_Value                      54000000
#define MX_USART6Freq_Value                     108000000
#define MX_USBFreq_Value                        216000000
#define MX_WatchDogFreq_Value                   32000
#define MX_LPTIM1Freq_Value                     54000000
#define MX_SPDIFRXFreq_Value                    192000000
#define MX_MCO1PinFreq_Value                    16000000
#define MX_MCO2PinFreq_Value                    216000000

/*-------------------------------- CORTEX_M7  --------------------------------*/

#define MX_CORTEX_M7                            1

/* GPIO Configuration */

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/*-------------------------------- TIM3       --------------------------------*/

#define MX_TIM3                                 1

/* GPIO Configuration */

/* Pin PD2 */
#define MX_S_TIM3_ETR_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM3_ETR_Pin                       PD2
#define MX_S_TIM3_ETR_GPIOx                     GPIOD
#define MX_S_TIM3_ETR_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM3_ETR_GPIO_Pin                  GPIO_PIN_2
#define MX_S_TIM3_ETR_GPIO_AF                   GPIO_AF2_TIM3
#define MX_S_TIM3_ETR_GPIO_Mode                 GPIO_MODE_AF_PP

/*-------------------------------- USART6     --------------------------------*/

#define MX_USART6                               1

#define MX_USART6_VM                            VM_ASYNC

/* GPIO Configuration */

/* Pin PG9 */
#define MX_USART6_RX_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART6_RX_Pin                        PG9
#define MX_USART6_RX_GPIOx                      GPIOG
#define MX_USART6_RX_GPIO_PuPd                  GPIO_PULLUP
#define MX_USART6_RX_GPIO_Pin                   GPIO_PIN_9
#define MX_USART6_RX_GPIO_AF                    GPIO_AF8_USART6
#define MX_USART6_RX_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PG14 */
#define MX_USART6_TX_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART6_TX_Pin                        PG14
#define MX_USART6_TX_GPIOx                      GPIOG
#define MX_USART6_TX_GPIO_PuPd                  GPIO_PULLUP
#define MX_USART6_TX_GPIO_Pin                   GPIO_PIN_14
#define MX_USART6_TX_GPIO_AF                    GPIO_AF8_USART6
#define MX_USART6_TX_GPIO_Mode                  GPIO_MODE_AF_PP

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

#endif  /* __MX_DEVICE_H */

